[workspace]
members = ["packages/*", "contracts/*"]
resolver = "2"

[profile.release.package.sg721]
codegen-units = 1
incremental = false

[profile.release.package.sg721-vending]
codegen-units = 1
incremental = false

[profile.release.package.sg-whitelist]
codegen-units = 1
incremental = false

[profile.release.package.royalty-group]
codegen-units = 1
incremental = false

[profile.release.package.sg-utils]
codegen-units = 1
incremental = false

[profile.release.package.sg-std]
codegen-units = 1
incremental = false

[profile.release.package.factory]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
